# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: "123"
  Google_api_ID: 1052282545216-tbba5kcs1c66c0opb9ohv9ck9ahdn6l2.apps.googleusercontent.com
  Google_api_key: GuuBwkTQfBlwktoPouzMVwlD

test:
  secret_key_base: "456"
  Google_api_ID: 1052282545216-tbba5kcs1c66c0opb9ohv9ck9ahdn6l2.apps.googleusercontent.com
  Google_api_key: GuuBwkTQfBlwktoPouzMVwlD

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  Google_api_ID: <%= ENV["GOOGLE_API_ID"] %>
  Google_api_key: <%= ENV["GOOGLE_API_KEY"] %>
